
export { deepMerge } from './deepMerge'
export { curry } from './curry'
export { debounce } from './debounce'
export { throttle } from './throttle'
export { hasCn } from './hasCn'
export { getUrlParam } from './getUrlParam'
export { uniqueArray } from './uniqueArray'
export { escapeHtml } from './escapeHtml'



export { isFn } from './is/isFn'
export { isStr } from './is/isStr'
export { isNum } from './is/isNum'
export { isPlainObject } from './is/isPlainObject'
export { isUndef } from './is/isUndef'
export { isArray } from './is/isArray'
export { isPromise } from './is/isPromise'
export { isNaN } from './is/isNaN'
export { isSymbol } from './is/isSymbol'
export { isNull } from './is/isNull'
export { isReg } from './is/isReg'
export { isBool } from './is/isBool'
export { isDate } from './is/isDate'
export { isEmail } from './is/isEmail'
export { isIdCard } from './is/isIdCard'
export { isMobile } from './is/isMobile'
export { isPostCode } from './is/isPostCode'
export { isType } from './is/isType'
export { isFile } from './is/isFile'
export { isBlob } from './is/isBlob'
export { isBottom } from './is/isBottom'
